[package]
name = "tensorflow-sys"
version = "0.10.0"
license = "Apache-2.0"
authors = [
  "Adam Crume <acrume@google.com>",
  "Ivan Ukhov <ivan.ukhov@gmail.com>",
]
description = "The package provides bindings to TensorFlow."
documentation = "https://tensorflow.github.io/rust"
homepage = "https://github.com/tensorflow/rust"
repository = "https://github.com/tensorflow/rust"
build = "build.rs"
links = "tensorflow"

[dependencies]
libc = "0.2"

[build-dependencies]
curl = "0.4"
flate2 = "0.2"
pkg-config = "0.3"
semver = "0.8"
tar = "0.4"

[features]
tensorflow_gpu = []
# This is for testing purposes; users should not use this.
nightly = []
