on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

name: Continuous integration

env:
  CARGO_TERM_COLOR: always
  TF_RUST_BUILD_FROM_SRC: false
  # RUSTFLAGS: "-D warnings"  # it needs some works to enable this flag

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Check macOS architecture
        if: matrix.os == 'macos-latest'
        id: check-arch
        run: |
          arch_name="$(uname -m)"
          echo "Detected architecture: $arch_name"
          echo "::set-output name=architecture::$arch_name"
      - name: Setup environment for Apple Silicon
        if: matrix.os == 'macos-latest' && steps.check-arch.outputs.architecture == 'arm64'
        run: |
          bash ~/miniconda.sh -b -p $HOME/miniconda
          source ~/miniconda/bin/activate
          conda install -c apple tensorflow-deps
      - name: Setup environment for AMD
        if: matrix.os == 'macos-latest' && steps.check-arch.outputs.architecture == 'x86_64'
        run: |
          python3 -m venv ~/venv-metal
          source ~/venv-metal/bin/activate
          python -m pip install -U pip
      - name: Setup environment for macOS
        if: matrix.os == 'macos-latest'
        run: |
          python -m pip install tensorflow
          python -m pip install tensorflow-metal
      # Install pip and pytest
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/workflows/requirements.txt
      - name: Execute test-all
        run: ./test-all
        shell: bash

#  clippy:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        rust:
#          - beta
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions-rs/toolchain@v1
#        with:
#          profile: minimal
#          toolchain: ${{ matrix.rust }}
#          override: true
#          components: clippy
#      - run: cargo clippy